name: Docker Image CI

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag robert2411/ollama-pre-loaded:latest --build-arg items="tinydolphin tinyllama codegemma"
